import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import GoTop from "./Components/GoTop";
import FloatingActionButton from "./Components/FloatingActionButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Provisa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` bg-white ${inter.className} overflow-x-hidden`}>
        <FloatingActionButton />
        <GoTop />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
